# Generated by Django 4.1.5 on 2023-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_desc_featproduct_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featproduct',
            name='IsFiction',
            field=models.BooleanField(default=True),
        ),
    ]
